name: Build Release
run-name: Build Release by ${{ github.actor }}
on: 
  release:
    branches:
        - qt5
    types: [ published ]
jobs:
  build-linux:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - { arch: x86_64, profile: x86_64 }
          - { arch: aarch64, profile: armv8 }
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore conan cache
        uses: actions/cache/restore@v3
        with:
          path: .conan2/p
          key: conan2-linux-${{ matrix.arch }}
          restore-keys: |
            conan2-linux-${{ matrix.arch }}
        
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: x86_64 build binary and appimage
        if: ${{ matrix.arch == 'x86_64' }}
        uses: addnab/docker-run-action@v3
        with:
          image: wyzdwdz/appimage-ubuntu18.04
          options: -v ${{ github.workspace }}:/var/www --platform linux/amd64
          shell: bash
          run: |
            cd /var/www
            export CONAN_HOME=/var/www/.conan2
            apt update && apt -y install lld-10
            update-alternatives --install /usr/bin/ld ld /usr/lib/llvm-10/bin/lld 10
            conan export --version 8.0.1 -nr 3rdparty/harfbuzz_expt
            conan config install .github/conan2-linux
            conan install . -b missing -pr:h ${{ matrix.profile }} -pr:b x86_64
            source ./build/Release/generators/conanbuild.sh
            cmake --preset conan-release
            cmake --build --preset conan-release -j
            cmake --install build/Release --prefix install --strip
            linuxdeploy --appdir=./AppDir -e ./install/bin/assfonts -d ./src/resources/assfonts.desktop -i ./src/resources/icon.png --icon-filename=assfonts --custom-apprun=./src/resources/AppRun
            appimagetool ./AppDir assfonts-${{ github.ref_name }}-x86_64-Linux.AppImage

      - name: aarch64 build binary
        if: ${{ matrix.arch == 'aarch64' }}
        uses: addnab/docker-run-action@v3
        with:
          image: wyzdwdz/appimage-ubuntu18.04:latest
          options: -v ${{ github.workspace }}:/var/www --platform linux/amd64
          shell: bash
          run: |
            cd /var/www
            export CONAN_HOME=/var/www/.conan2
            apt update && apt -y install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu lld-10
            update-alternatives --install /usr/bin/ld ld /usr/lib/llvm-10/bin/lld 10
            cp -f .github/apt-lists/amd64-sources.list /etc/apt/sources.list
            cp -f .github/apt-lists/arm64-sources.list /etc/apt/sources.list.d/
            dpkg --add-architecture arm64
            apt update
            export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
            conan export --version 8.0.1 -nr 3rdparty/harfbuzz_expt
            conan config install .github/conan2-linux
            conan install . -b missing -pr:h ${{ matrix.profile }} -pr:b x86_64
            source ./build/Release/generators/conanbuild.sh
            cmake --preset conan-release
            cmake --build --preset conan-release -j
            cmake --install build/Release --prefix install --strip

      - name: aarch64 build appimage
        if: ${{ matrix.arch == 'aarch64' }}
        uses: addnab/docker-run-action@v3
        with:
          image: wyzdwdz/appimage-ubuntu18.04:latest
          options: -v ${{ github.workspace }}:/var/www --platform linux/arm64
          shell: bash
          run: |
            cd /var/www
            apt update && apt -y install squashfs-tools libxcb1
            linuxdeploy --appdir=./AppDir -e ./install/bin/assfonts -d ./src/resources/assfonts.desktop -i ./src/resources/icon.png --icon-filename=assfonts --custom-apprun=./src/resources/AppRun
            ln -sf assfonts.png ./AppDir/.DirIcon
            mksquashfs ./AppDir AppDir.squashfs -root-owned -noappend
            wget https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-aarch64
            cat runtime-aarch64 >> assfonts-${{ github.ref_name }}-aarch64-Linux.AppImage
            cat AppDir.squashfs >> assfonts-${{ github.ref_name }}-aarch64-Linux.AppImage

      - name: upload AppImages
        uses: actions/upload-artifact@v3
        with:
          name: release-appimage-${{ matrix.arch }}
          path: assfonts-${{ github.ref_name }}-${{ matrix.arch }}-Linux.AppImage
          if-no-files-found: error

      - name: set read permission to conan cache
        run: sudo chmod -R 777 .conan2/p

      - name: save conan cache
        uses: actions/cache/save@v3
        with:
          path: .conan2/p
          key: conan2-linux-${{ matrix.arch }}-${{ hashFiles('.conan2/p/cache.sqlite3') }}

  build-windows:
    runs-on: windows-2022
    defaults:
      run:
        shell: powershell
    strategy:
      matrix:
        include:
          - { arch: x86_64, profile: x86_64 }
          - { arch: aarch64, profile: armv8 }
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore conan cache
        uses: actions/cache/restore@v3
        with:
          path: .conan2/p
          key: conan2-windows-${{ matrix.arch }}
          restore-keys: |
            conan2-windows-${{ matrix.arch }}

      - name: install cmake
        uses: lukka/get-cmake@latest

      - name: install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 2.0.4

      - name: set CONAN_HOME
        run: Add-Content -Path $env:GITHUB_ENV -Value "CONAN_HOME=${{ github.workspace }}\.conan2"

      - name: aarch64 fix conan recipes
        if: ${{ matrix.arch == 'aarch64' }}
        run: |
          conan export .github\recipes\libffi_fix -nr --version 3.4.4
          conan export .github\recipes\libiconv_fix -nr --version 1.17
          conan export .github\recipes\qt5_fix -nr --version 5.15.10

      - name: aarch64 add tools to PATH
        if: ${{ matrix.arch == 'aarch64' }}
        run: Add-Content -Path $env:GITHUB_PATH -Value ((Get-Location -PSProvider FileSystem).Path + "\.github\tools")

      - name: build executable binary
        run: |
          conan export --version 8.0.1 -nr 3rdparty\harfbuzz_expt
          conan config install .github\conan2-windows
          conan install . -b missing -pr:h ${{ matrix.profile }} -pr:b x86_64
          .\build\generators\conanbuild.bat
          cmake --preset conan-default
          cmake --build --preset conan-release -j
          cmake --install build --prefix install

      - name: copy and rename
        run: Copy-Item -Path ".\install\bin\assfonts.exe" -Destination "assfonts-${{ github.ref_name }}-${{ matrix.arch }}-Windows.exe" -Force

      - name: x86_64 upx compress
        if: ${{ matrix.arch == 'x86_64' }}
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: assfonts-${{ github.ref_name }}-${{ matrix.arch }}-Windows.exe
          args: -fq9

      - name: upload exe
        uses: actions/upload-artifact@v3
        with:
          name: release-exe-${{ matrix.arch }}
          path: assfonts-${{ github.ref_name }}-${{ matrix.arch }}-Windows.exe
          if-no-files-found: error

      - name: save conan cache
        uses: actions/cache/save@v3
        with:
          path: .conan2/p
          key: conan2-windows-${{ matrix.arch }}-${{ hashFiles('.conan2/p/cache.sqlite3') }}

  # build-macos:
  #   runs-on: macos-12
  #   defaults:
  #     run:
  #       shell: bash
  #   strategy:
  #     matrix:
  #       include:
  #         - { arch: x86_64, profile: x86_64 }
  #         - { arch: aarch64, profile: armv8 }
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v3

  #     - name: restore conan cache
  #       uses: actions/cache/restore@v3
  #       with:
  #           path: .conan2/p
  #           key: conan2-macos-${{ matrix.arch }}
  #           restore-keys: |
  #             conan2-macos-${{ matrix.arch }}

  #     - name: install cmake
  #       uses: lukka/get-cmake@latest

  #     - name: install Conan
  #       id: conan
  #       uses: turtlebrowser/get-conan@main
  #       with:
  #         version: 2.0.4

  #     - name: set CONAN_HOME
  #       run: echo "CONAN_HOME=${{ github.workspace }}/.conan2" >> "$GITHUB_ENV"

  #     - name: aarch64 fix conan recipes
  #       if: ${{ matrix.arch == 'aarch64' }}
  #       run: |
  #         conan export .github/recipes/qt5_fix -nr --version 5.15.10

  #     - name: build executable binary
  #       run: |
  #         conan export --version 8.0.1 -nr 3rdparty/harfbuzz_expt
  #         conan config install .github/conan2-macos
  #         conan install . -b missing -pr:h ${{ matrix.profile }} -pr:b x86_64
  #         source ./build/Release/generators/conanbuild.sh
  #         cmake --preset conan-release
  #         cmake --build --preset conan-release --target package -j

  #     - name: rename
  #       run: mv -f assfonts.dmg assfonts-${{ github.ref_name }}-${{ matrix.arch }}-macOS.dmg

  #     - name: upload dmg
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: release-dmg-${{ matrix.arch }}
  #         path: assfonts-${{ github.ref_name }}-${{ matrix.arch }}-macOS.dmg
  #         if-no-files-found: error

  #     - name: save conan cache
  #       uses: actions/cache/save@v3
  #       with:
  #           path: .conan2/p
  #           key: conan2-macos-${{ matrix.arch }}-${{ hashFiles('.conan2/p/cache.sqlite3') }}

  release:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    needs: [ build-linux, build-windows ]
    # needs: [ build-linux, build-windows, build-macos ]
    steps:
      - name: download AppImages x86_64
        uses: actions/download-artifact@v3
        with:
          name: release-appimage-x86_64
          
      - name: download AppImages aarch64
        uses: actions/download-artifact@v3
        with:
          name: release-appimage-aarch64

      - name: download exe x86_64
        uses: actions/download-artifact@v3
        with:
          name: release-exe-x86_64

      - name: download exe aarch64
        uses: actions/download-artifact@v3
        with:
          name: release-exe-aarch64

      # - name: download dmg x86_64
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: release-dmg-x86_64
  
      # - name: download dmg aarch64
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: release-dmg-aarch64

      - name: calculate hash
        run: |
          sha256sum assfonts-${{ github.ref_name }}-x86_64-Linux.AppImage > assfonts-${{ github.ref_name }}-x86_64-Linux.AppImage.sha256sum
          sha256sum assfonts-${{ github.ref_name }}-aarch64-Linux.AppImage > assfonts-${{ github.ref_name }}-aarch64-Linux.AppImage.sha256sum
          sha256sum assfonts-${{ github.ref_name }}-x86_64-Windows.exe > assfonts-${{ github.ref_name }}-x86_64-Windows.exe.sha256sum
          sha256sum assfonts-${{ github.ref_name }}-aarch64-Windows.exe > assfonts-${{ github.ref_name }}-aarch64-Windows.exe.sha256sum
          # sha256sum assfonts-${{ github.ref_name }}-x86_64-macOS.dmg > assfonts-${{ github.ref_name }}-x86_64-macOS.dmg.sha256sum
          # sha256sum assfonts-${{ github.ref_name }}-aarch64-macOS.dmg > assfonts-${{ github.ref_name }}-aarch64-macOS.dmg.sha256sum

      - name: edit release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: assfonts-${{ github.ref_name }}-*
          tag: ${{ github.ref }}
          overwrite: false
          file_glob: true
