name: Build Release
run-name: Build Release by ${{ github.actor }}
on: 
  release:
    types: [ published ]
  push:
    branches: [ main ] 

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [x86_64, aarch64, armhf, i686]
        include:
          - arch: x86_64
            profile: x64
          - arch: aarch64
            profile: arm64
          - arch: armhf
            profile: armv7l
          - arch: i686
            profile: x86
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
        
      - name: build binary
        uses: addnab/docker-run-action@v3
        with:
          image: wyzdwdz/assfonts-amd64:latest
          options: -v ${{ github.workspace }}:/var/www
          shell: bash
          run: |
            source ~/.bashrc
            cd /var/www
            cp ./.github/linux/CMakeUserPresets.json .
            cmake . --preset linux-${{ matrix.profile }}
            cmake --build . --target install --preset linux-${{ matrix.profile }}-release -j
            mv ./out/install/linux-${{ matrix.profile }}/bin/assfonts assfonts-${{ github.ref_name }}-${{ matrix.arch }}-Linux

      - name: upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: release-Linux-${{ matrix.arch }}
          path: assfonts*-${{ github.ref_name }}-${{ matrix.arch }}-Linux*
          if-no-files-found: error
          
      - name: upload issue
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.profile }}-issue
          path: out/build/linux-${{ matrix.profile }}/vcpkg_installed/vcpkg/issue_body.md
          
  release:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    needs: [ build-linux ]
    if: github.event_name == 'release'
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: download Linux x86_64
        uses: actions/download-artifact@v4
        with:
          name: release-Linux-x86_64

      - name: download Linux aarch64
        uses: actions/download-artifact@v4
        with:
          name: release-Linux-aarch64

      - name: download Linux armhf
        uses: actions/download-artifact@v4
        with:
          name: release-Linux-armhf
          
      - name: download Linux i686
        uses: actions/download-artifact@v4
        with:
          name: release-Linux-i686

      - name: create zips
        run: |
          sudo apt-get install -y zip
          mkdir -p ./share/doc/assfonts
          cp LICENSE LICENSE.txt
          cp NEWS NEWS.txt
          cp NOTICE NOTICE.txt
          cp LICENSE NEWS NOTICE ./share/doc/assfonts/
          mkdir -p ./share/man/man1
          gzip -k ./doc/man/assfonts.1
          cp ./doc/man/assfonts.1.gz ./share/man/man1/
          mkdir bin
          cp -f assfonts-${{ github.ref_name }}-x86_64-Linux ./bin/assfonts
          chmod +x ./bin/assfonts
          zip -r assfonts-${{ github.ref_name }}-x86_64-Linux.zip bin share LICENSE.txt NEWS.txt NOTICE.txt
          rm -rf bin share LICENSE.txt NEWS.txt NOTICE.txt
          
          mkdir bin
          cp -f assfonts-${{ github.ref_name }}-aarch64-Linux ./bin/assfonts
          chmod +x ./bin/assfonts
          zip -r assfonts-${{ github.ref_name }}-aarch64-Linux.zip bin share LICENSE.txt NEWS.txt NOTICE.txt
          rm -rf bin share LICENSE.txt NEWS.txt NOTICE.txt
          
          mkdir bin
          cp -f assfonts-${{ github.ref_name }}-armhf-Linux ./bin/assfonts
          chmod +x ./bin/assfonts
          zip -r assfonts-${{ github.ref_name }}-armhf-Linux.zip bin share LICENSE.txt NEWS.txt NOTICE.txt
          rm -rf bin share LICENSE.txt NEWS.txt NOTICE.txt
          
          mkdir bin
          cp -f assfonts-${{ github.ref_name }}-i686-Linux ./bin/assfonts
          chmod +x ./bin/assfonts
          zip -r assfonts-${{ github.ref_name }}-i686-Linux.zip bin share LICENSE.txt NEWS.txt NOTICE.txt
          rm -rf bin share LICENSE.txt NEWS.txt NOTICE.txt

      - name: upload release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            assfonts-${{ github.ref_name }}-*-Linux*
          
