name: Build Release
run-name: Build Release by ${{ github.actor }}
on: 
  release:
    types: [ published ]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: wyzdwdz/appimage-ubuntu18.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: build executable binary
        run: ./build.sh

      - name: build AppImage
        run: |
          linuxdeploy --appdir=./AppDir -e ./install/bin/assfonts -d ./src/resources/assfonts.desktop -i ./src/resources/icon.png --icon-filename=assfonts
          appimagetool ./AppDir assfonts-${{ github.ref_name }}-x86_64.AppImage

      - name: upload AppImages
        uses: actions/upload-artifact@v3
        with:
          name: release-appimage-amd64
          path: assfonts-${{ github.ref_name }}-x86_64.AppImage
          if-no-files-found: error

  build-windows:
    runs-on: windows-2019
    steps:
      - name: install msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: install cmake
        uses: lukka/get-cmake@latest

      - name: install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 2.0.4
      
      - name: checkout
        uses: actions/checkout@v3

      - name: build executable binary
        run: .\build.bat

      - name: copy and rename
        run: echo f | xcopy /f /y .\install\bin\assfonts.exe assfonts-${{ github.ref_name }}-x86_64.exe

      - name: upx compress
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: assfonts-${{ github.ref_name }}-x86_64.exe
          args: -fq9

      - name: upload exe
        uses: actions/upload-artifact@v3
        with:
          name: release-exe-amd64
          path: assfonts-${{ github.ref_name }}-x86_64.exe
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: [ build-linux, build-windows ]
    steps:
      - name: download AppImages
        uses: actions/download-artifact@v3
        with:
          name: release-appimage-amd64

      - name: download exe
        uses: actions/download-artifact@v3
        with:
          name: release-exe-amd64

      - name: calculate hash
        run: |
          sha256sum assfonts-${{ github.ref_name }}-x86_64.AppImage > assfonts-${{ github.ref_name }}-x86_64.AppImage.sha256sum
          sha256sum assfonts-${{ github.ref_name }}-x86_64.exe > assfonts-${{ github.ref_name }}-x86_64.exe.sha256sum

      - name: edit release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: assfonts-${{ github.ref_name }}-*
          tag: ${{ github.ref }}
          overwrite: false
          file_glob: true
