name: Build linux AppImage
run-name: Build linux AppImage by ${{ github.actor }}
on: 
  push:
    branches: [ imgui ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 2.0.4
          
      - name: Detect Conan profile
        run: conan profile detect

      - name: Conan version
        run: echo "${{ steps.conan.outputs.version }}"
        
      - name: Start build script
        run: sudo ./build.sh
