name: Macos Test
run-name: Macos Test by ${{ github.actor }}
on: push
jobs:
  build-macos:
    runs-on: macos-12
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - { arch: x86_64, profile: x86_64 }
          - { arch: aarch64, profile: armv8 }
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore conan cache
        uses: actions/cache/restore@v3
        with:
            path: .conan2/p
            key: conan2-macos-${{ matrix.arch }}
            restore-keys: |
              conan2-macos-${{ matrix.arch }}

      - name: install cmake
        uses: lukka/get-cmake@latest

      - name: install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 2.0.4

      - name: set CONAN_HOME
        run: echo "CONAN_HOME=${{ github.workspace }}/.conan2" >> "$GITHUB_ENV"

      - name: build executable binary
        run: |
          conan export --version 7.3.0 -nr 3rdparty/harfbuzz_expt
          conan config install .github/conan2-macos
          conan install . -b missing -pr:h ${{ matrix.profile }} -pr:b x86_64
          cd build
          source conanbuild.sh
          cmake .. --preset conan-release
          # cmake --build --preset conan-release --target package -j
          cmake --build --preset conan-release -j
          cmake --install Release --prefix ../install --strip
          cd ..

      - name: rename
        # run: mv -f assfonts.dmg assfonts-${{ github.ref_name }}-${{ matrix.arch }}-macOS.dmg
        run: cp -f ./install/assfonts assfonts-${{ github.ref_name }}-${{ matrix.arch }}-macOS

      - name: upload dmg
        uses: actions/upload-artifact@v3
        with:
          name: release-dmg-${{ matrix.arch }}
          # path: assfonts-${{ github.ref_name }}-${{ matrix.arch }}-macOS.dmg
          path: assfonts-${{ github.ref_name }}-${{ matrix.arch }}-macOS
          if-no-files-found: error

      # - name: save conan cache
      #   uses: actions/cache/save@v3
      #   with:
      #       path: .conan2/p
      #       key: conan2-macos-${{ matrix.arch }}-${{ hashFiles('.conan2/p/cache.sqlite3') }}

  release:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    needs: [ build-macos ]
    steps:
      - name: download dmg x86_64
        uses: actions/download-artifact@v3
        with:
          name: release-dmg-x86_64

      - name: download dmg aarch64
        uses: actions/download-artifact@v3
        with:
          name: release-dmg-aarch64

      - name: calculate hash
        run: |
          # sha256sum assfonts-${{ github.ref_name }}-x86_64-macOS.dmg > assfonts-${{ github.ref_name }}-x86_64-macOS.dmg.sha256sum
          # sha256sum assfonts-${{ github.ref_name }}-aarch64-macOS.dmg > assfonts-${{ github.ref_name }}-aarch64-macOS.dmg.sha256sum
          sha256sum assfonts-${{ github.ref_name }}-x86_64-macOS > assfonts-${{ github.ref_name }}-x86_64-macOS.sha256sum
          sha256sum assfonts-${{ github.ref_name }}-aarch64-macOS > assfonts-${{ github.ref_name }}-aarch64-macOS.sha256sum

      - name: edit release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: assfonts-${{ github.ref_name }}-*
          tag: ${{ github.ref }}
          overwrite: false
          file_glob: true
          make_latest: false