name: Macos Test
run-name: Macos Test by ${{ github.actor }}
on: push
jobs:
  build-macos:
    runs-on: macos-12
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - { arch: x86_64, profile: x86_64 }
          - { arch: aarch64, profile: armv8 }
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install cmake
        uses: lukka/get-cmake@latest

      - name: install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 2.0.4

      - name: build executable binary
        run: |
          conan config install .github/conan2-macos
          conan install . -b missing -pr:h ${{ matrix.profile }} -pr:b x86_64
          cd build
          ./conanbuild.sh
          cmake .. --preset conan-release
          cmake --build --preset conan-release -j
          cmake --install Release --prefix ../install
          cd ..
          ls -a ./install