name: Macos Test
run-name: Macos Test by ${{ github.actor }}
on: push
jobs:
  build-macos:
    runs-on: macos-12
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - { arch: x86_64, profile: x86_64 }
          - { arch: aarch64, profile: armv8 }
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore conan cache
        uses: actions/cache/restore@v3
        with:
            path: .conan2/p
            key: conan2-macos-${{ matrix.arch }}
            restore-keys: |
              conan2-macos-${{ matrix.arch }}

      - name: install cmake
        uses: lukka/get-cmake@latest

      - name: install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 2.0.4

      - name: set CONAN_HOME
        run: echo "CONAN_HOME=${{ github.workspace }}/.conan2" >> "$GITHUB_ENV"

      - name: build executable binary
        run: |
          conan export --version 7.3.0 -nr 3rdparty/harfbuzz_expt
          conan config install .github/conan2-macos
          conan install . -b missing -pr:h ${{ matrix.profile }} -pr:b x86_64
          cd build
          source conanbuild.sh
          cmake .. --preset conan-release
          cmake --build . --target package -j
          cmake --install . --prefix ../install --strip
          cd ..
          ls -a ./install
          ls -a .
          ls -a ./build
          ls -a ./build/Release

      # - name: save conan cache
      #   uses: actions/cache/save@v3
      #   with:
      #       path: .conan2/p
      #       key: conan2-macos-${{ matrix.arch }}-${{ hashFiles('.conan2/p/cache.sqlite3') }}